### ISSUE TITLE
Adding Chapter Special Operator

### ISSUE THREAD

**Issue by mslmn** [noaione/nao-manga-rls#5]
This might be a stupid question but how do I add the special chapter operators `#` or `x` to chapters? When using `releases`, there's only an option for special naming which puts text in square brackets.

**Comment by noaione** [comment]
That's for extra chapter like 5.5, etc. Sometimes you can see it on the ToC where they include bonus/extra/omake chapter.

You can also use it for chapter that are split into parts (1.1, 1.2, etc.)

**Comment by noaione** [comment]
Something to add, if your numbering is below .5, it will add the actual chapter number in the filename.

ex: `Title - c001x1 (c001.1) (v01) - p000 [dig] [Publisher] [Credit]`

Mainly used for split chapters, so when you use autosplit it will be `001.1.cbz` and not `001.5.cbz`

**Comment by noaione** [comment]
I mean, the operation are mainly used in `releases`, `pack`, and `tag`

**Comment by noaione** [comment]
https://github.com/noaione/nao-manga-rls/assets/34302902/6e182209-3cc1-4bce-9b18-969098f6aa80

This is what it looks like, command used:
`nmanga releases -hq --no-tag -t "The Strongest Sage With the Weakest Crest" -pub "Square Enix" target_folder`

The folder just contains an images with naming: `Strongest Sage - v12 - p000.jpg`
Transform into:
- `The Strongest Sage With the Weakest Crest - c036 (v12) - p000 [Cover] [dig] [AAA] [Square Enix] [nao] {HQ}`
- `The Strongest Sage With the Weakest Crest - c036 (v12) - p001 [dig] [AAA] [Square Enix] [nao] {HQ}`
- `The Strongest Sage With the Weakest Crest - c038x1 (v12) - p185 [dig] [Short Story] [Square Enix] [nao] {HQ}`
- etc.

You basically can put anything before the volume number since it will be modified anyway by the `-t/--title` parameter.
